import { Geist, Geist_Mono } from "next/font/google";
import { ReactNode } from "react";
import { getDictionary } from "@/utils/getDictionary";
import DictionariesProvider from "@core/contexts/dictionariesContext";
import type { Locale } from "@configs/i18n";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Netflix Clone",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: { lang: Locale };
}) {
  const { lang } = params;
  const dictionary = await getDictionary(lang);

  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DictionariesProvider dictionaries={dictionary}>
          {children}
        </DictionariesProvider>
      </body>
    </html>
  );
}
